#!/bin/bash

# absolute path to this script. Works for OSX, Linux and BSD
SCRIPTPATH=$(perl -MCwd=realpath -e "print realpath '$0'")
SCRIPTPATH=$(dirname "$SCRIPTPATH");

# Include config
source "$SCRIPTPATH/config.sh";


# Check args count
if [ $# -eq 0 ]
  then
   echo "$APP_CLI_NAME v$APP_CLI_VER";
   echo "Create a new virtual host";
   echo "  Usage: $0 'hostname'";
   exit 1;
  fi

# params
conf_p="$DIR_CONF"
conf_ext=".conf"
conf_file="$conf_p/$1$conf_ext"

# owner
own_name="$USR_NAME";
own_grp="$USR_GROUP";

HOST_OWN="$USR_NAME:$USR_GROUP";
if [ "$USR_GROUP" = "root" ]; then
  HOST_OWN="$USR_NAME";
fi;

# Sites path
www_path="$DIR_HOSTS/hosts"

# folder with html files, eidted by proezdov
public_html="$1"

host_path="$www_path/$1"

# check hosts path
if [ ! -d "$DIR_HOSTS" ]; then
  sudo mkdir -p "$DIR_HOSTS";
  sudo chmod 777 "$DIR_HOSTS";
fi;

# create host path
sudo mkdir -p "$host_path";
sudo mkdir "$host_path/$public_html";

# permissions
sudo chmod 777 "$host_path"
sudo chmod 777 "$host_path/$public_html";

# ownership
sudo chown "$HOST_OWN" "$host_path";
sudo chown "$HOST_OWN" "$host_path/$public_html";

echo "* Host directory: $host_path";
echo "* Documents root: '$host_path/$public_html'";
# Test index.php
#echo '<?php phpinfo(); ?>' > "$host_path/$public_html/index.php";

#Added by Proezdov
#sudo chown "$HOST_OWN" "$host_path/$public_html/index.php";
sudo echo "127.0.0.1 $1" >> /etc/hosts;

# Create config
sudo cp "$SCRIPTPATH/example-yii2.conf" "$conf_file";

function repl_args {
  sed -i -e "s#%$1%#$2#g" "$conf_file";
}

# replace hostname
# sed -i -e "s#%HOSTRING%#$1#g" "$conf_file";
repl_args "HOSTRING" "$1";
repl_args "HOSTPATH" "$DIR_HOSTS";

# Enable site
sudo a2ensite "$1" >/dev/null 2>&1;

echo "* Host config: $conf_file";
echo "Configuration and directory for host '$1' were created successfuly";
echo "To edit configuration, run 'edit-host $1'";
echo "Trying Apache restart";
sudo apachectl restart;
echo "Please check the result.";
